version: '{build}'

image: Visual Studio 2015

environment:
  matrix:
    - COMPILER: MinGW
      GENERATOR: "MinGW Makefiles"
    - COMPILER: msvc15
      GENERATOR: "Visual Studio 14 2015"

configuration:
  - Release

platform:
  - Win32

before_build:
  - cd WindowsServer
  - mkdir _build
  - cd _build
  - rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
  - if [%COMPILER%]==[MinGW] set PATH=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%

build_script:
  - cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -Dgtest_disable_pthreads=ON ..
  - cmake --build . --config %CONFIGURATION%